#!/bin/bash

install() {
  # prepare vars
  local name="$DESKTOP_CORE_NAME"

  log::info "[$(timestamp)][desktop][$name] preparing ..."

  # get system os/arch
  local os="$DESKTOP_OS"
  local arch="$DESKTOP_OS_ARCH"
  local kernel="$DESKTOP_OS_KERNEL"
  local platform="$DESKTOP_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$DESKTOP_USER_BIN_DIR"
  local cache_dir="$DESKTOP_CACHE_DIR"
  local tmp_dir="$DESKTOP_TMP_DIR"

  #
  case $platform in
  darwin)
    platform="mac"
    ;;
  *)
    log::error "[$(timestamp)] unsupport platform: $platform"
    return 1
    ;;
  esac

  case $arch in
  arm64) ;;

  amd64)
    arch="x64"
    ;;
  *)
    log::error "[$(timestamp)] unsupport arch: $arch"
    return 1
    ;;
  esac

  # files
  local cache_file="$cache_dir/${DESKTOP_CORE_VERSION}-${platform}-${arch}.dmg"
  # local source_bin_file="./$name"

  # prepare context
  log::info "[$(timestamp)][desktop][$name] context: $tmp_dir ..."
  cd $tmp_dir

  if [ -f "$cache_file" ]; then
    log::info "[$(timestamp)][desktop][$name] found cache at $cache_file ..."
  else
    # reference: https://github.com/9seconds/iterm2/releases
    # example:
    #   https://github.com/electerm/electerm/releases/download/v1.25.16/electerm-1.25.16-mac-arm64.dmg
    #   https://github.com/electerm/electerm/releases/download/v1.25.16/electerm-1.25.16-mac-x64.dmg
    # generate url
    local url="${DESKTOP_CORE_RELEASE_DOWNLOAD}/${DESKTOP_CORE_VERSION}/electron-${DESKTOP_CORE_VERSION#v}-${platform}-${arch}.dmg"
    log::debug "[$(timestamp)][desktop][$name][$kernel][$arch] url: $url, file: ${cache_file}, tmp_dir: $tmp_dir"

    # download
    log::info "[$(timestamp)][desktop][$name] downloading from $url ..."
    os::download $cache_file $url
  fi

  # install
  log::info "[$(timestamp)][desktop][$name] installing $cache_file ..."
  # os::install $source_bin_file $usr_bin_dir $name
  install::dmg $cache_file electerm electerm.app "/Volumes/electerm\ 1.25.16-arm64"

  # clean
  log::info "[$(timestamp)][desktop][$name] cleaning ..."
  rm -rf $tmp_dir
}

export -f install
